global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'llm_cache_proxy'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi-proxy:8000', 'host.docker.internal:8000']
